# Site settings
title: Things That Shouldn't Work But Do
email: christopher.luebbemeier@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  It's mainly things concerning other things computing things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://christopher-l.github.io" # the base hostname & protocol for your site
github_username:  christopher-l

# Build settings
markdown: kramdown
